wsf: Handle relative imports and import module.wsf for main
Imports prefixed with @ are located in the search path (currently only
wslib). Otherwise, imports are relative to the importing file. If a
module.wsf file exists adjacent to the main file, it is automatically
imported without a scope (i.e., those labels can be used without
importing and prefixing with the module name).

diff --git a/wsf-assemble b/wsf-assemble
--- a/wsf-assemble
+++ b/wsf-assemble
@@ -11,13 +11,6 @@ out="$2"
 
 WSLIB="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
 
-gsed -Ef "$WSLIB"/wsf.sed "$prog" > "$out"
-final_inst=$(awk '/./{line=$0} END{print line}' "$out")
-if ! grep -Eq '^(call|jmp|j[zn]) |^(ret|exit)$' <<< "$final_inst"; then
-  echo "$out: Program does not end with a control flow instruction: $final_inst" >&2
-  exit 1
-fi
-
 imports=()
 in_imports() {
   local import
@@ -35,8 +28,8 @@ resolve_import() {
       echo "$file: Unable to resolve import: $import.wsf is a directory"
       return 1
     fi
-    if [ -d "$import" ]; then
-      echo "$file: Unable to resolve import: both $import.wsf and $import/ exit"
+    if [ -e "$import/module.wsf" ]; then
+      echo "$file: Unable to resolve import: both $import.wsf and $import/module.wsf exit"
       return 1
     fi
     echo "$import.wsf"
@@ -57,27 +50,42 @@ resolve_import() {
 get_imports() {
   local file="$1"
   local module="$2"
+  file="$(realpath -s "$file")"
   imports=("${imports[@]}" "$module:$file")
+
+  local module_file="${file%/*}/module.wsf"
+  if [ "$module" = '' ] && ! in_imports ":$module_file" && [ -f "$module_file" ]; then
+    get_imports "$module_file" ''
+  fi
+
   local import
   while read -r import; do
     local import_module
     case "$import" in
-      import:*) import="${import#import:}"; import_module="$import" ;;
-      export:*) import="${import#export:}"; import_module="$file" ;;
+      import:*)
+        import="${import#import:}"
+        import_module="${import#@}"
+        import_module="${import_module##*/}"
+      ;;
+      export:*)
+        import="${import#export:}"
+        import_module="$module"
+      ;;
     esac
-    import_module="${import_module%/module.wsf}"
-    import_module="${import_module##*/}"
-    import_module="${import_module%.wsf}"
 
-    local import_file
-    if ! import_file="$(resolve_import "$file" "$import")"; then
-      local local_fail="$import_file"
-      if ! import_file="$(resolve_import "$file" "$WSLIB/$import")"; then
-        echo "$local_fail" >&2
-        echo "$import_file" >&2
-        exit 1
-      fi
+    local import_path
+    if [[ "$import" = @* ]]; then
+      import="${import#@}"
+      import_path="$WSLIB/$import"
+    else
+      import_path="$(dirname "$file")/$import"
     fi
+    local import_file
+    if ! import_file="$(resolve_import "$file" "$import_path")"; then
+      echo "$import_file" >&2
+      exit 1
+    fi
+
     if ! in_imports "$import_module:$import_file"; then
       get_imports "$import_file" "$import_module"
     fi
@@ -89,11 +97,23 @@ get_imports() {
 
 get_imports "$prog" ''
 
+gsed -Ef "$WSLIB"/wsf.sed "$prog" > "$out"
+final_inst=$(awk '/./{line=$0} END{print line}' "$out")
+if ! grep -Eq '^(call|jmp|j[zn]) |^(ret|exit)$' <<< "$final_inst"; then
+  echo "$out: Program does not end with a control flow instruction: $final_inst" >&2
+  exit 1
+fi
+
 for import in "${imports[@]:1}"; do
   module="${import%%:*}"
   import_file="${import#*:}"
-  gsed -E "
-    s/\b(call|jmp|j[zn=<>]|j[<>]=|jeof)\s+(\.?)([A-za-z0-9_-]+)( |$)/\1 \2$module.\3\4/
-    s/\b(\.?)([A-za-z0-9_-]+:)( |$)/\1$module.\2\3/
-  " "$import_file"
-done | gsed -Ef "$WSLIB"/wsf.sed >> "$out"
+  gsed -Ef "$WSLIB"/wsf.sed "$import_file" |
+  if [ "$module" = '' ]; then cat
+  else
+    gsed -E "
+      s/\b(call|jmp|jz|jn) (\.?)([A-za-z0-9_-]+)( |$)/\1 \2$module.\3\4/g
+      s/(^| )(\.?)([A-Za-z0-9_-]+:)/\1\2$module.\3/g"
+  fi
+done >> "$out"
+
+gsed -E -i'' 's/(^| )\./\1_/g; s/\./__/g' "$out"
