wsf: Introduce modules and export
A module is either a single .wsf file or a directory containing
module.wsf. `import` includes the given module, with the file or
directory name, respectively, as the module name. `export` includes the
given module, but under the exporting module's name. A module.wsf file
typically re-exports the relevant .wsf files in its directory, excluding
test files.

diff --git a/wsf-assemble b/wsf-assemble
--- a/wsf-assemble
+++ b/wsf-assemble
@@ -27,31 +27,73 @@ in_imports() {
   return 1
 }
 
-get_imports() {
+resolve_import() {
   local file="$1"
-  imports=("${imports[@]}" "$file")
-  local import
-  while read -r import; do
-    local import_file="$import.wsf"
-    if [ ! -f "$import_file" ]; then
-      import_file="$WSLIB/$import_file"
-      if [ ! -f "$import_file" ]; then
-        echo "$file: Unable to resolve import: $import" >&1; exit 1
-      fi
+  local import="$2"
+  if [ -e "$import.wsf" ]; then
+    if [ -d "$import.wsf" ]; then
+      echo "$file: Unable to resolve import: $import.wsf is a directory"
+      return 1
     fi
-    if ! in_imports "$import_file"; then
-      get_imports "$import_file"
+    if [ -d "$import" ]; then
+      echo "$file: Unable to resolve import: both $import.wsf and $import/ exit"
+      return 1
     fi
-  done < <(gsed -En 's/(^|\s)"([^"]+)"\s+import\b/\2/p' "$file")
+    echo "$import.wsf"
+    return 0
+  elif [ -e "$import/module.wsf" ]; then
+    if [ -d "$import/module.wsf" ]; then
+      echo "$file: Unable to resolve import: $import/module.wsf is a directory"
+      return 1
+    fi
+    echo "$import/module.wsf"
+    return 0
+  else
+    echo "$file: Unable to resolve import: $import"
+    return 1
+  fi
 }
 
-get_imports "$prog"
+get_imports() {
+  local file="$1"
+  local module="$2"
+  imports=("${imports[@]}" "$module:$file")
+  local import
+  while read -r import; do
+    local import_module
+    case "$import" in
+      import:*) import="${import#import:}"; import_module="$import" ;;
+      export:*) import="${import#export:}"; import_module="$file" ;;
+    esac
+    import_module="${import_module%/module.wsf}"
+    import_module="${import_module##*/}"
+    import_module="${import_module%.wsf}"
+
+    local import_file
+    if ! import_file="$(resolve_import "$file" "$import")"; then
+      local local_fail="$import_file"
+      if ! import_file="$(resolve_import "$file" "$WSLIB/$import")"; then
+        echo "$local_fail" >&2
+        echo "$import_file" >&2
+        exit 1
+      fi
+    fi
+    if ! in_imports "$import_module:$import_file"; then
+      get_imports "$import_file" "$import_module"
+    fi
+  done < <(gsed -En '
+    s/(^|\s)"([^"]+)"\s+import\b/import:\2/p
+    s/(^|\s)"([^"]+)"\s+export\b/export:\2/p
+  ' "$file")
+}
+
+get_imports "$prog" ''
 
 for import in "${imports[@]:1}"; do
-  package="${import%/*}"
-  package="${package##*/}"
+  module="${import%%:*}"
+  import_file="${import#*:}"
   gsed -E "
-    s/\b(call|jmp|j[zn=<>]|j[<>]=|jeof)\s+(\.?)([A-za-z0-9_-]+)( |$)/\1 \2$package.\3\4/
-    s/\b(\.?)([A-za-z0-9_-]+:)( |$)/\1$package.\2\3/
-  " "$import"
+    s/\b(call|jmp|j[zn=<>]|j[<>]=|jeof)\s+(\.?)([A-za-z0-9_-]+)( |$)/\1 \2$module.\3\4/
+    s/\b(\.?)([A-za-z0-9_-]+:)( |$)/\1$module.\2\3/
+  " "$import_file"
 done | gsed -Ef "$WSLIB"/wsf.sed >> "$out"
